version: '3.6'
services:
  memcached:
    container_name: ddev-${DDEV_SITENAME}-memcached
    image: memcached:latest
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    ports:
      - "11211"
    networks:
      - default